### ISSUE TITLE
evolution-data-server missing on base image

### ISSUE THREAD

**Issue by BrainBlasted** [Vanilla-OS/vanilla-base-meta#8]
EDS is required on the host system for applications like GNOME Calendar and GNOME Contacts. Without it present, they will not function correctly. For example, the Contacts flatpak immediately crashes without EDS.

**Comment by kbdharun** [comment]
> EDS is required on the host system for applications like GNOME Calendar and GNOME Contacts. Without it present, they will not function correctly. For example, the Contacts flatpak immediately crashes without EDS.

This, Is a known issue, I will add it soon. Thanks for the report.
